version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DEBUG=true
      - SECRET_KEY=dev-secret-key
    volumes:
      - .:/app
    restart: unless-stopped
    
  # Future: Add database service
  # db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: burn_tokens
  #     POSTGRES_USER: burn_user
  #     POSTGRES_PASSWORD: burn_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data: