name: 'Setup Python and Poetry'
description: 'Sets up Python, installs Poetry, optionally caches dependencies, and installs project dependencies'

inputs:
  python-version:
    description: 'Python version to set up'
    required: true
    default: '3.13'
  enable-cache:
    description: 'Whether to enable Poetry dependency caching'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: true
    
    - name: Cache Poetry dependencies
      if: inputs.enable-cache == 'true'
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          venv-${{ runner.os }}-${{ inputs.python-version }}-
    
    - name: Install dependencies
      shell: bash
      run: poetry install --no-interaction